require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/profile_users", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProfileUser. As you add validations to ProfileUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProfileUser.create! valid_attributes
      get profile_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      profile_user = ProfileUser.create! valid_attributes
      get profile_user_url(profile_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_profile_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      profile_user = ProfileUser.create! valid_attributes
      get edit_profile_user_url(profile_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProfileUser" do
        expect {
          post profile_users_url, params: { profile_user: valid_attributes }
        }.to change(ProfileUser, :count).by(1)
      end

      it "redirects to the created profile_user" do
        post profile_users_url, params: { profile_user: valid_attributes }
        expect(response).to redirect_to(profile_user_url(ProfileUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProfileUser" do
        expect {
          post profile_users_url, params: { profile_user: invalid_attributes }
        }.to change(ProfileUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post profile_users_url, params: { profile_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested profile_user" do
        profile_user = ProfileUser.create! valid_attributes
        patch profile_user_url(profile_user), params: { profile_user: new_attributes }
        profile_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the profile_user" do
        profile_user = ProfileUser.create! valid_attributes
        patch profile_user_url(profile_user), params: { profile_user: new_attributes }
        profile_user.reload
        expect(response).to redirect_to(profile_user_url(profile_user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        profile_user = ProfileUser.create! valid_attributes
        patch profile_user_url(profile_user), params: { profile_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested profile_user" do
      profile_user = ProfileUser.create! valid_attributes
      expect {
        delete profile_user_url(profile_user)
      }.to change(ProfileUser, :count).by(-1)
    end

    it "redirects to the profile_users list" do
      profile_user = ProfileUser.create! valid_attributes
      delete profile_user_url(profile_user)
      expect(response).to redirect_to(profile_users_url)
    end
  end
end
