source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0', '>= 7.0.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma'

gem 'sass-rails'
gem 'webpacker'
gem 'turbolinks'
gem 'jbuilder'
# gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap'
# gem 'bundler', '~> 2.2', '>= 2.2.33'
gem 'optimist'
gem 'yarn'
#CSS
gem 'bootstrap'
#Java Script
gem 'jquery-rails'

gem "mini_portile2"

# Variáveis de ambiente
gem 'figaro'
# Formulario simples
gem 'simple_form'
# Geenciameto de usuário
gem 'devise'
# Engine html
gem 'haml'
gem 'haml-rails'
# gem "erb2haml", :group => development
gem 'html2haml'

# Paginação
gem 'kaminari'
# gem 'bootstrap-kaminari-views'
# Busca
gem 'ransack'
# Melhorar select
# gem 'select2-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Colocados neste projeto
  gem 'pry'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'rspec-rails'
  # gem 'solargraph'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  # Inserido neste projeto
  gem 'mailcatcher'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'psych'