# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Anunciavaga' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'anunciavaga' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1936, 1048)
    @driver.find_element(:css, 'h1').click
    @driver.find_element(:link_text, 'Publicar Vaga').click
    @driver.find_element(:id, 'position_name').click
    @driver.find_element(:id, 'position_name').send_keys('auxia de escritoio')
    @driver.find_element(:id, 'position_publish').click
    @driver.find_element(:id, 'position_city').click
    @driver.find_element(:id, 'position_city').send_keys('buriticupu')
    @driver.find_element(:id, 'position_state').click
    dropdown = @driver.find_element(:id, 'position_state')
    dropdown.find_element(:xpath, "//option[. = 'Maranhão']").click
    @driver.find_element(:id, 'position_summary').click
    @driver.find_element(:id, 'position_summary').send_keys('asaaaaaaaaaa')
    @driver.find_element(:id, 'position_description').click
    @driver.find_element(:id, 'position_description').send_keys('aaaaaaaaaaaaaaaa')
    @driver.find_element(:name, 'commit').click
  end
end
