# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Cadastralogin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'cadastralogin' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1936, 1048)
    @driver.find_element(:id, 'navbarsExampleDefault').click
    @driver.find_element(:link_text, 'Login/Cadastro').click
    @driver.find_element(:id, 'user_email').send_keys('kaikkelv2@gmail.com')
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:css, '.form-check').click
    @driver.find_element(:id, 'user_remember_me').click
    @driver.find_element(:name, 'commit').click
  end
end
